### ISSUE TITLE
The digit-five dataset is no longer exist

### ISSUE THREAD

**Issue by Trgtuan10** [jonas-lippl/FACT#2]

**Comment by jonas-lippl** [comment]
Hi Trgtuan, the Digit-five dataset was provided by Peng et al. and unfortunately the link no longer exists. Maybe you can try this one: https://wjdcloud.blob.core.windows.net/dataset/dg5.tar.gz from [this](https://github.com/jindongwang/transferlearning/issues/378) related issue.

**Comment by Trgtuan10** [comment]
Thanks @jonas-lippl
